In [33]:
import numpy as np

Code
import numpy as np
import pandas as pd

In [100]:
df = pd.read_excel (io='C:/Users/Tobiloba/Desktop/DieselLogSheet/Oshodi_August_ 2022_Diesel Logsheet.xlsx')
# read_file.to_csv (r'C:\Users\Tobiloba\Desktop\DieselLogSheet\CSV\DieselLogSheet.csv', index = None, header=True)

In [101]:
# dropping the first 12 rows
df.drop(index=list(range(0,14)), inplace=True)
df = df[['Unnamed: 0','Unnamed: 7','Unnamed: 8','Unnamed: 14','Unnamed: 19']]

In [102]:
df.rename(columns = {'Unnamed: 0':'Date', 'Unnamed: 7':'Diesel_Tank_Opening_Quantity', 'Unnamed: 8':'Quantity_of_Diesel_Supplied'\
                    , 'Unnamed: 14':'Diesel_Tank_Closing_Quantity', 'Unnamed: 19':'Difference_In_Diesel_Quantity'}, inplace = True)

In [103]:
df

,Date,Diesel_Tank_Opening_Quantity,Quantity_of_Diesel_Supplied,Diesel_Tank_Closing_Quantity,Difference_In_Diesel_Quantity
14,2022-01-04 00:00:00,2180,NaN,2160,20
15,2022-01-05 00:00:00,2160,NaN,2120,40
16,2022-01-06 00:00:00,2120,NaN,2080,40
17,2022-01-06 00:00:00,NaN,NaN,NaN,NaN
18,2022-01-07 00:00:00,2080,NaN,2020,60
...,...,...,...,...,...
181,2022-08-25 00:00:00,4430,NaN,4400,30
182,2022-08-26 00:00:00,NEPA,NaN,NIL,NEPA
183,2022-08-29 00:00:00,NEPA,NaN,NIL,NEPA
184,2022-08-30 00:00:00,4400,NaN,4350,50
185,2022-08-31 00:00:00,4350,NaN,4300,50

In [104]:
# removing all na values based on Diesel_Tank_Opening_Quantity
df = df[df['Diesel_Tank_Opening_Quantity'].notna()]
#drop rows that contain NEPA 
df = df[df.Diesel_Tank_Opening_Quantity != "NEPA"]
# Replacing all NaN values with 0
df.fillna(0, inplace=True)
df.replace(['NIL'],[0], inplace=True)

# Structuring the datatypes
df['Date'] = df['Date'].astype('datetime64')
df['Diesel_Tank_Opening_Quantity'] = df['Diesel_Tank_Opening_Quantity'].astype('int')
df['Quantity_of_Diesel_Supplied'] = df['Quantity_of_Diesel_Supplied'].astype('int')
df['Diesel_Tank_Closing_Quantity'] = df['Diesel_Tank_Closing_Quantity'].astype('int')
df['Difference_In_Diesel_Quantity'] = df['Difference_In_Diesel_Quantity'].astype('int')

In [105]:
df

,Date,Diesel_Tank_Opening_Quantity,Quantity_of_Diesel_Supplied,Diesel_Tank_Closing_Quantity,Difference_In_Diesel_Quantity
14,2022-01-04,2180,0,2160,20
15,2022-01-05,2160,0,2120,40
16,2022-01-06,2120,0,2080,40
18,2022-01-07,2080,0,2020,60
19,2022-01-10,2020,0,1950,70
...,...,...,...,...,...
179,2022-08-23,4520,0,4450,70
180,2022-08-24,4450,0,4430,20
181,2022-08-25,4430,0,4400,30
184,2022-08-30,4400,0,4350,50
185,2022-08-31,4350,0,4300,50

In [108]:
df['Difference_In_Diesel_Quantity_Calc'] = df['Diesel_Tank_Opening_Quantity'] - df['Diesel_Tank_Closing_Quantity']

In [109]:
df

,Date,Diesel_Tank_Opening_Quantity,Quantity_of_Diesel_Supplied,Diesel_Tank_Closing_Quantity,Difference_In_Diesel_Quantity,Difference_In_Diesel_Quantity_Calc
14,2022-01-04,2180,0,2160,20,20
15,2022-01-05,2160,0,2120,40,40
16,2022-01-06,2120,0,2080,40,40
18,2022-01-07,2080,0,2020,60,60
19,2022-01-10,2020,0,1950,70,70
...,...,...,...,...,...,...
179,2022-08-23,4520,0,4450,70,70
180,2022-08-24,4450,0,4430,20,20
181,2022-08-25,4430,0,4400,30,30
184,2022-08-30,4400,0,4350,50,50
185,2022-08-31,4350,0,4300,50,50

In [110]:
# Checking if correct
df['Truth'] = df['Difference_In_Diesel_Quantity'] == df['Difference_In_Diesel_Quantity_Calc']

df['Truth'].value_counts()

In [116]:
n_steps = 2
def rolling_diff(x):
    return x.iloc[-1] - x.iloc[0]

df['Refill_Check']=df.Diesel_Tank_Opening_Quantity.rolling(window=n_steps).apply(rolling_diff).fillna(-1)

df

,Date,Diesel_Tank_Opening_Quantity,Quantity_of_Diesel_Supplied,Diesel_Tank_Closing_Quantity,Difference_In_Diesel_Quantity,Difference_In_Diesel_Quantity_Calc,Truth,Refill_Check
14,2022-01-04,2180,0,2160,20,20,True,-1.0
15,2022-01-05,2160,0,2120,40,40,True,-20.0
16,2022-01-06,2120,0,2080,40,40,True,-40.0
18,2022-01-07,2080,0,2020,60,60,True,-40.0
19,2022-01-10,2020,0,1950,70,70,True,-60.0
...,...,...,...,...,...,...,...,...
179,2022-08-23,4520,0,4450,70,70,True,4520.0
180,2022-08-24,4450,0,4430,20,20,True,-70.0
181,2022-08-25,4430,0,4400,30,30,True,-20.0
184,2022-08-30,4400,0,4350,50,50,True,-30.0
185,2022-08-31,4350,0,4300,50,50,True,-50.0

In [117]:
df['Refilling Check2'] = df['Refill_Check'] > 0
df

,Date,Diesel_Tank_Opening_Quantity,Quantity_of_Diesel_Supplied,Diesel_Tank_Closing_Quantity,Difference_In_Diesel_Quantity,Difference_In_Diesel_Quantity_Calc,Truth,Refill_Check,Refilling Check2
14,2022-01-04,2180,0,2160,20,20,True,-1.0,False
15,2022-01-05,2160,0,2120,40,40,True,-20.0,False
16,2022-01-06,2120,0,2080,40,40,True,-40.0,False
18,2022-01-07,2080,0,2020,60,60,True,-40.0,False
19,2022-01-10,2020,0,1950,70,70,True,-60.0,False
...,...,...,...,...,...,...,...,...,...
179,2022-08-23,4520,0,4450,70,70,True,4520.0,True
180,2022-08-24,4450,0,4430,20,20,True,-70.0,False
181,2022-08-25,4430,0,4400,30,30,True,-20.0,False
184,2022-08-30,4400,0,4350,50,50,True,-30.0,False
185,2022-08-31,4350,0,4300,50,50,True,-50.0,False

### Identifing site name

In [195]:
import os
import pandas as pd
import numpy as np
import glob
pd.reset_option('^display.', silent=True)
os.chdir(r"C:\\Users\\Tobiloba\\Desktop\\DieselLogSheet\\main")

globbed_files = glob.glob("*.xlsx") #creates a list of all csv files

globbed_files

['Aba_August_2022.xlsx',
 'Apapa_August_2022.xlsx',
 'HeadOffice_August_2022.xlsx',
 'IkejaBG_ August_ 2022.xlsx',
 'IkejaSG_August_ 2022.xlsx',
 'OkeArin_August_2022.xlsx',
 'Onitsha2_August_2022.xlsx',
 'Onitsha_August_2022.xlsx',
 'Oshodi_August_ 2022.xlsx',
 'Tradefair_August_2022.xlsx']

In [196]:
data = []
for xlsx in globbed_files:
    frame = pd.read_excel(xlsx)
    frame['filename'] = os.path.basename(xlsx)
    data.append(frame)
    df = pd.concat(data)
    

site = df['filename']

In [197]:
site = df['filename'].str.split('_', expand=True)[[0]]

Aba           840
IkejaSG       409
IkejaBG       379
Onitsha       379
Tradefair     345
Apapa         258
OkeArin       197
Oshodi        186
Onitsha2       38
HeadOffice     23
dtype: int64

In [153]:
conditions = [ (site[0] == 'Aba')\
             ,(site[0] == 'IkejaSG')\
             ,(site[0] == 'IkejaBG')\
             ,(site[0] == 'Onitsha')\
              ,(site[0] == 'Tradefair')\
              ,(site[0] == 'Apapa')\
              ,(site[0] == 'OkeArin')\
              ,(site[0] == 'Oshodi')\
              ,(site[0] == 'Onitsha2')\
              ,(site[0] == 'HeadOffice')\
             ]

# create a list of the values we want to assign for each condition
values = ['Aba','Ikeja SG','Ikeja BG','Onitsha','Tradefair','Apapa','OkeArin','Oshodi','Onitsha2','Head Office']

# create a new column and use np.select to assign values to it using our lists as arguments
df['site'] = np.select(conditions, values)
# capitalizing the site names 
df['site'] = df['site'].str.capitalize()

In [154]:
# dropping the first 12 rows
df.drop(index=list(range(0,14)), inplace=True)
df = df[['Unnamed: 0','Unnamed: 7','Unnamed: 8','Unnamed: 14','Unnamed: 19','site']]

In [155]:
df.rename(columns = {'Unnamed: 0':'Date', 'Unnamed: 7':'Diesel_Tank_Opening_Quantity', 'Unnamed: 8':'Quantity_of_Diesel_Supplied'\
                    , 'Unnamed: 14':'Diesel_Tank_Closing_Quantity', 'Unnamed: 19':'Difference_In_Diesel_Quantity'}, inplace = True)

In [1]:
# removing all na values based on Diesel_Tank_Opening_Quantity
df = df[df['Diesel_Tank_Opening_Quantity'].notna()]
#drop rows that contain NEPA 
df = df[df.Diesel_Tank_Opening_Quantity != "NEPA"]
df = df[df.Date != "Date (DD/MM/YYYY)"]
# Replacing all NaN values with 0
df.fillna(0, inplace=True)
df.replace(['NIL'],[0], inplace=True)

NameError: name 'df' is not defined

In [ ]:
def remove_whitespace():
    for col in df.columns:
        df[col].str.strip()

In [181]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
df = df.replace('LITRES','', regex=True)
df = df.replace('LTRES','', regex=True)
df = df.replace('was supplied','', regex=True)
df = df.replace('was supiled','', regex=True)

# removing all whitespaces
remove_whitespace()



df

,Date,Diesel_Tank_Opening_Quantity,Quantity_of_Diesel_Supplied,Diesel_Tank_Closing_Quantity,Difference_In_Diesel_Quantity,site
26,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
53,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
98,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
156,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
178,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
204,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
226,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
245,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
247,0,,Michael,11:26:00,0,Aba
269,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
293,0,PHCN METER READING for the Day (KWH),REPORTING OFFICER MORNING/OPENING,TOTAL DAILY OPERATIONAL HOURS,0,Aba
17,2022-01-04 00:00:00,1320,0,1320,0,Apapa
18,2022-01-05 00:00:00,1320,0,1170,150,Apapa
19,2022-01-06 00:00:00,1170,0,1170,0,Apapa
20,2022-01-07 00:00:00,1170,0,1170,0,Apapa
23,2022-01-10 00:00:00,1170,0,1170,0,Apapa
24,2022-01-11 00:00:00,1170,0,1170,0,Apapa
25,2022-01-12 00:00:00,1170,0,1170,0,Apapa
26,2022-01-13 00:00:00,1170,0,1170,0,Apapa
27,2022-01-14 00:00:00,1170,0,1170,0,Apapa
30,2022-01-17 00:00:00,1170,0,1170,0,Apapa
31,2022-01-18 00:00:00,1170,0,1170,0,Apapa
32,2022-01-19 00:00:00,1170,0,970,200,Apapa
33,2022-01-20 00:00:00,970,0,970,0,Apapa
34,2022-01-21 00:00:00,970,0,970,0,Apapa
37,2022-01-24 00:00:00,970,0,970,0,Apapa
38,2022-01-25 00:00:00,970,0,970,0,Apapa
39,2022-01-26 00:00:00,970,0,970,0,Apapa
40,2022-01-27 00:00:00,970,0,970,0,Apapa
41,2022-01-28 00:00:00,970,0,790,180,Apapa
44,2022-01-31 00:00:00,790,0,790,0,Apapa
45,2022-02-01 00:00:00,1960,0,1960,0,Apapa
46,2022-02-02 00:00:00,1960,0,1960,0,Apapa
47,2022-02-03 00:00:00,1960,0,1960,0,Apapa
48,2022-02-04 00:00:00,1960,0,1820,140,Apapa
51,2022-02-07 00:00:00,1820,0,1820,0,Apapa
52,2022-02-08 00:00:00,1820,0,1820,0,Apapa
53,2022-02-09 00:00:00,1820,0,1820,0,Apapa
54,2022-02-10 00:00:00,1820,0,1820,0,Apapa
55,2022-02-11 00:00:00,1820,0,1670,150,Apapa
58,2022-02-14 00:00:00,1670,0,1670,0,Apapa
59,2022-02-15 00:00:00,1670,0,1670,0,Apapa
60,2022-02-16 00:00:00,1670,0,1670,0,Apapa
61,2022-02-17 00:00:00,1670,0,1670,0,Apapa
62,2022-02-18 00:00:00,1670,0,1510,160,Apapa
65,2022-02-21 00:00:00,1510,0,1510,0,Apapa
66,2022-02-22 00:00:00,1510,0,1510,0,Apapa
67,2022-02-23 00:00:00,1510,0,1510,0,Apapa
68,2022-02-24 00:00:00,1510,0,1340,170,Apapa
69,2022-02-25 00:00:00,1340,0,1340,0,Apapa
72,2022-02-28 00:00:00,1340,0,1340,0,Apapa
73,2022-03-01 00:00:00,1340,0,1340,0,Apapa
74,2022-03-02 00:00:00,1340,0,1340,0,Apapa
75,2022-03-03 00:00:00,1340,0,1200,140,Apapa
76,2022-03-04 00:00:00,1200,0,1200,0,Apapa
79,2022-03-07 00:00:00,1200,0,1200,0,Apapa
80,2022-03-08 00:00:00,1200,0,1040,160,Apapa
81,2022-03-09 00:00:00,1040,0,1040,0,Apapa
82,2022-03-10 00:00:00,1040,0,1040,0,Apapa
83,2022-03-11 00:00:00,1040,0,1040,0,Apapa
86,2022-03-14 00:00:00,1040,,850,190,Apapa
87,2022-03-15 00:00:00,850,0,850,0,Apapa
88,2022-03-16 00:00:00,850,0,850,0,Apapa
89,2022-03-17 00:00:00,850,0,700,150,Apapa
90,2022-03-18 00:00:00,700,0,700,0,Apapa
93,2022-03-21 00:00:00,700,0,540,160,Apapa
94,2022-03-22 00:00:00,540,0,540,0,Apapa
95,2022-03-23 00:00:00,540,0,540,0,Apapa
96,2022-03-24 00:00:00,540,0,540,0,Apapa
97,2022-03-25 00:00:00,540,0,330,210,Apapa
100,2022-03-28 00:00:00,330,0,330,0,Apapa
101,2022-03-29 00:00:00,330,0,330,0,Apapa
102,2022-03-30 00:00:00,330,0,330,0,Apapa
103,2022-03-31 00:00:00,330,0,240,90,Apapa
104,2022-04-01 00:00:00,240,0,240,0,Apapa
107,2022-04-04 00:00:00,240,0,240,0,Apapa
108,2022-04-05 00:00:00,240,1300,1500,40,Apapa
109,2022-04-06 00:00:00,1500,0,1270,230,Apapa
110,2022-04-07 00:00:00,1270,0,1270,0,Apapa
111,2022-04-08 00:00:00,1270,0,1270,0,Apapa
114,2022-04-11 00:00:00,1270,0,1140,130,Apapa
115,2022-04-12 00:00:00,1140,0,1140,0,Apapa
116,2022-04-13 00:00:00,1140,0,1140,0,Apapa
117,2022-04-14 00:00:00,1140,0,1140,0,Apapa
122,2022-04-19 00:00:00,1140,0,980,160,Apapa
123,2022-04-20 00:00:00,980,0,980,0,Apapa
124,2022-04-21 00:00:00,980,0,980,0,Apapa
125,2022-04-22 00:00:00,980,0,980,0,Apapa
128,2022-04-25 00:00:00,980,0,790,190,Apapa
129,2022-04-26 00:00:00,790,0,790,0,Apapa
130,2022-04-27 00:00:00,790,0,790,0,Apapa
131,2022-04-28 00:00:00,790,0,790,0,Apapa
132,2022-04-29 00:00:00,790,0,790,0,Apapa
133,2022-04-30 00:00:00,790,0,790,0,Apapa
137,2022-05-04 00:00:00,790,0,790,0,Apapa
138,2022-05-05 00:00:00,790,0,790,0,Apapa
139,2022-05-06 00:00:00,790,0,790,0,Apapa
142,2022-05-09 00:00:00,790,0,790,0,Apapa
143,2022-05-10 00:00:00,790,0,610,180,Apapa
144,2022-05-11 00:00:00,610,0,610,0,Apapa
145,2022-05-12 00:00:00,610,0,1980,0,Apapa
146,2022-05-13 00:00:00,1980,0,1980,0,Apapa
149,2022-05-16 00:00:00,1980,0,1760,220,Apapa
150,2022-05-17 00:00:00,1760,0,1760,0,Apapa
151,2022-05-18 00:00:00,1760,0,1760,0,Apapa
152,2022-05-19 00:00:00,1760,0,1620,140,Apapa
153,2022-05-20 00:00:00,1620,0,1620,0,Apapa
156,2022-05-23 00:00:00,1620,0,1620,0,Apapa
157,2022-05-24 00:00:00,1620,0,1620,0,Apapa
158,2022-05-25 00:00:00,1620,0,1470,150,Apapa
159,2022-05-26 00:00:00,1470,0,1470,0,Apapa
160,2022-05-27 00:00:00,1470,0,1470,0,Apapa
161,2022-05-28 00:00:00,1470,0,1470,0,Apapa
163,2022-05-30 00:00:00,1470,0,1320,150,Apapa
164,2022-05-31 00:00:00,1320,0,1320,0,Apapa
165,2022-06-01 00:00:00,1320,0,1320,0,Apapa
166,2022-06-02 00:00:00,1320,0,1320,0,Apapa
167,2022-06-03 00:00:00,1320,0,1140,180,Apapa
170,2022-06-06 00:00:00,1140,0,1140,0,Apapa
171,2022-06-07 00:00:00,1140,0,1140,0,Apapa
172,2022-06-08 00:00:00,1140,0,930,210,Apapa
173,2022-06-09 00:00:00,930,0,930,0,Apapa
174,2022-06-10 00:00:00,930,0,930,0,Apapa
178,2022-06-14 00:00:00,930,0,930,0,Apapa
179,2022-06-15 00:00:00,930,0,740,190,Apapa
180,2022-06-16 00:00:00,740,0,740,0,Apapa
181,2022-06-17 00:00:00,740,0,740,0,Apapa
184,2022-06-20 00:00:00,740,1300,2010,30,Apapa
185,2022-06-21 00:00:00,2010,0,1840,170,Apapa
186,2022-06-22 00:00:00,1840,0,1840,0,Apapa
187,2022-06-23 00:00:00,1840,0,1840,0,Apapa
188,2022-06-24 00:00:00,1840,0,1840,0,Apapa
191,2022-06-27 00:00:00,1840,0,1840,0,Apapa
192,2022-06-28 00:00:00,1840,0,1700,140,Apapa
193,2022-06-29 00:00:00,1700,0,1700,0,Apapa
194,2022-06-30 00:00:00,1700,0,1700,0,Apapa
195,2022-07-01 00:00:00,1700,0,1560,140,Apapa
198,2022-07-04 00:00:00,1560,0,1560,0,Apapa
199,2022-07-05 00:00:00,1560,0,1560,0,Apapa
200,2022-07-06 00:00:00,1560,0,1560,0,Apapa
201,2022-07-07 00:00:00,1560,0,1560,0,Apapa
202,2022-07-08 00:00:00,1560,0,1560,0,Apapa
207,2022-07-13 00:00:00,1560,0,1420,140,Apapa
208,2022-07-14 00:00:00,1420,0,1420,0,Apapa
209,2022-07-15 00:00:00,1420,0,1420,0,Apapa
212,2022-07-18 00:00:00,1420,0,1420,0,Apapa
213,2022-07-19 00:00:00,1420,0,1420,0,Apapa
214,2022-07-20 00:00:00,1420,0,1270,150,Apapa
215,2022-07-21 00:00:00,1270,0,1270,0,Apapa
216,2022-07-22 00:00:00,1270,0,1270,0,Apapa
219,2022-07-25 00:00:00,1270,0,1270,0,Apapa
220,2022-07-26 00:00:00,1270,0,1120,150,Apapa
221,2022-07-27 00:00:00,1120,0,1120,0,Apapa
222,2022-07-28 00:00:00,1120,0,1120,0,Apapa
223,2022-07-29 00:00:00,1120,0,1120,0,Apapa
224,2022-07-30 00:00:00,1120,0,1120,0,Apapa
226,2022-08-01 00:00:00,1120,0,970,150,Apapa
227,2022-08-02 00:00:00,970,0,970,0,Apapa
228,2022-08-03 00:00:00,970,0,970,0,Apapa
229,2022-08-04 00:00:00,970,0,970,0,Apapa
230,2022-08-05 00:00:00,970,0,970,0,Apapa
233,2022-08-08 00:00:00,970,0,970,0,Apapa
234,2022-08-09 00:00:00,970,0,850,120,Apapa
235,2022-08-10 00:00:00,850,0,850,0,Apapa
236,2022-08-11 00:00:00,850,0,850,0,Apapa
237,2022-08-12 00:00:00,850,0,850,0,Apapa
240,2022-08-15 00:00:00,850,0,850,0,Apapa
241,2022-08-16 00:00:00,850,0,850,0,Apapa
242,2022-08-17 00:00:00,850,0,850,0,Apapa
243,2022-08-18 00:00:00,720,0,720,130,Apapa
244,19/08/2022,720,0,720,0,Apapa
247,2022-08-22 00:00:00,720,0,720,0,Apapa
248,2022-08-23 00:00:00,720,0,720,0,Apapa
249,2022-08-24 00:00:00,720,0,720,0,Apapa
250,2022-08-25 00:00:00,720,0,720,0,Apapa
251,2022-08-26 00:00:00,720,0,720,0,Apapa
254,2022-08-29 00:00:00,720,0,720,0,Apapa
255,2022-08-30 00:00:00,720,0,580,140,Apapa
256,2022-08-31 00:00:00,580,0,580,0,Apapa
19,2022-01-06 00:00:00,1100,0,882,218,Ikeja bg
30,2022-01-17 00:00:00,360,0,96,264,Ikeja bg
37,2022-01-24 00:00:00,4514,0,4214,300,Ikeja bg
45,2022-02-01 00:00:00,3887,0,3607,0,Ikeja bg
53,2022-02-09 00:00:00,3094,0,2762,18,Ikeja bg
61,2022-02-17 00:00:00,2572,0,2283,87,Ikeja bg
69,2022-02-25 00:00:00,2062,0,1744,137,Ikeja bg
75,2022-03-03 00:00:00,1571,0,1276,112,Ikeja bg
80,2022-03-08 00:00:00,1046,0,758,143,Ikeja bg
82,2022-03-10 00:00:00,576,0,293,82,Ikeja bg
88,2022-03-16 00:00:00,3814,0,3469,154,Ikeja bg
90,2022-03-18 00:00:00,3310,0,2965,140,Ikeja bg
93,2022-03-21 00:00:00,2776,0,2527,117,Ikeja bg
97,2022-03-25 00:00:00,2527,0,2213,120,Ikeja bg
198,2022-07-04 00:00:00,300,0,0,120,Ikeja bg
201,2022-07-07 00:00:00,288,0,0,60,Ikeja bg
213,2022-07-19 00:00:00,308,0,0,60,Ikeja bg
219,2022-07-25 00:00:00,320,0,0,72,Ikeja bg
223,2022-07-29 00:00:00,322,0,0,72,Ikeja bg
232,2022-08-07 00:00:00,331,0,0,72,Ikeja bg
242,2022-08-17 00:00:00,326,0,0,108,Ikeja bg
249,2022-08-24 00:00:00,306,0,0,6,Ikeja bg
19,2022-01-06 00:00:00,882,0,722,160,Ikeja sg
24,2022-01-11 00:00:00,722,0,532,190,Ikeja sg
30,2022-01-17 00:00:00,532,0,360,172,Ikeja sg
33,2022-01-20 00:00:00,4694,0,451,180,Ikeja sg
39,2022-01-26 00:00:00,4214,0,4027,187,Ikeja sg
46,2022-02-02 00:00:00,3422,0,3242,88,Ikeja sg
48,2022-02-04 00:00:00,3242,0,3094,62,Ikeja sg
58,2022-02-14 00:00:00,2762,0,2572,51,Ikeja sg
62,2022-02-18 00:00:00,3132,0,2947,12,Ikeja sg
65,2022-02-21 00:00:00,2282,0,2062,137,Ikeja sg
69,2022-02-25 00:00:00,2247,0,0,15,Ikeja sg
70,2022-02-26 00:00:00,1744,0,1571,48,Ikeja sg
76,2022-03-04 00:00:00,1276,0,1046,182,Ikeja sg
78,2022-03-06 00:00:00,758,0,576,40,Ikeja sg
84,2022-03-12 00:00:00,293,0,102,136,Ikeja sg
87,2022-03-15 00:00:00,4000,0,3814,103,Ikeja sg
89,2022-03-17 00:00:00,3469,0,3310,63,Ikeja sg
92,2022-03-20 00:00:00,2965,0,2776,96,Ikeja sg
97,2022-03-25 00:00:00,2213,0,1989,161,Ikeja sg
98,2022-03-26 00:00:00,1989,0,1849,140,Ikeja sg
197,2022-07-03 00:00:00,125,0,0,215,Ikeja sg
198,2022-07-04 00:00:00,230,0,0,90,Ikeja sg
199,2022-07-05 00:00:00,50,0,0,100,Ikeja sg
202,2022-07-08 00:00:00,220,0,0,18,Ikeja sg
214,2022-07-20 00:00:00,187,0,0,90,Ikeja sg
217,2022-07-23 00:00:00,210,0,0,84,Ikeja sg
221,2022-07-27 00:00:00,200,0,0,108,Ikeja sg
226,2022-08-01 00:00:00,222,0,0,15,Ikeja sg
234,2022-08-09 00:00:00,208,0,0,78,Ikeja sg
239,2022-08-14 00:00:00,138,0,0,120,Ikeja sg
244,2022-08-19 00:00:00,226,0,0,96,Ikeja sg
245,2022-08-20 00:00:00,96,0,0,168,Ikeja sg
247,2022-08-22 00:00:00,68,0,0,72,Ikeja sg
17,2022-01-04 00:00:00,1800,0,1750,50,Okearin
18,2022-01-05 00:00:00,1750,0,1680,70,Okearin
19,2022-01-06 00:00:00,1680,0,1680,0,Okearin
20,2022-01-07 00:00:00,1680,0,1600,80,Okearin
23,2022-01-10 00:00:00,1600,0,1600,0,Okearin
24,2022-01-11 00:00:00,1600,0,1500,100,Okearin
25,2022-01-12 00:00:00,1500,0,1500,0,Okearin
26,2022-01-13 00:00:00,1500,0,1400,100,Okearin
27,2022-01-14 00:00:00,1400,0,1400,0,Okearin
30,2022-01-17 00:00:00,1400,0,1300,100,Okearin
31,2022-01-18 00:00:00,1300,0,1300,0,Okearin
32,2022-01-19 00:00:00,1300,0,1200,100,Okearin
33,2022-01-20 00:00:00,1200,0,1200,0,Okearin
34,2022-01-21 00:00:00,1200,0,1200,0,Okearin
37,2022-01-24 00:00:00,1200,0,1150,50,Okearin
38,2022-01-25 00:00:00,1150,0,1100,50,Okearin
39,2022-01-26 00:00:00,1100,0,1100,0,Okearin
40,2022-01-27 00:00:00,1100,0,1000,100,Okearin
41,2022-01-28 00:00:00,1000,0,1000,0,Okearin
44,2022-01-31 00:00:00,1000,0,950,50,Okearin
45,2022-02-01 00:00:00,950,0,900,50,Okearin
46,2022-02-02 00:00:00,900,0,900,0,Okearin
47,2022-02-03 00:00:00,900,1100,850,50,Okearin
48,2022-02-04 00:00:00,1950,0,1900,50,Okearin
49,2022-02-07 00:00:00,1900,0,1850,50,Okearin
50,2022-02-08 00:00:00,1850,0,1850,0,Okearin
51,2022-02-09 00:00:00,1850,0,1850,0,Okearin
52,2022-02-10 00:00:00,1800,0,1800,0,Okearin
53,2022-02-11 00:00:00,1800,0,1700,100,Okearin
54,2022-02-14 00:00:00,1700,0,1700,0,Okearin
55,2022-02-15 00:00:00,1700,0,1650,50,Okearin
56,2022-02-16 00:00:00,1650,0,1650,0,Okearin
57,2022-02-17 00:00:00,1600,0,1550,50,Okearin
58,2022-02-18 00:00:00,1550,0,1500,50,Okearin
59,2022-02-21 00:00:00,1500,0,1500,0,Okearin
60,2022-02-22 00:00:00,1500,0,1400,100,Okearin
61,2022-02-23 00:00:00,1400,0,1400,0,Okearin
62,2022-02-24 00:00:00,1400,0,1350,50,Okearin
63,2022-02-25 00:00:00,1350,0,1250,100,Okearin
64,2022-02-28 00:00:00,1250,0,1250,0,Okearin
65,2022-03-01 00:00:00,1250,0,1200,50,Okearin
66,2022-03-02 00:00:00,1200,0,1200,0,Okearin
67,2022-03-03 00:00:00,1200,0,1150,50,Okearin
68,2022-03-04 00:00:00,1150,0,1150,0,Okearin
69,2022-03-07 00:00:00,1150,0,1100,50,Okearin
70,2022-03-08 00:00:00,1100,0,1050,50,Okearin
71,2022-03-09 00:00:00,1050,0,1050,0,Okearin
72,2022-03-10 00:00:00,1050,0,1000,50,Okearin
73,2022-03-11 00:00:00,1000,0,950,50,Okearin
74,2022-03-14 00:00:00,950,0,950,0,Okearin
75,2022-03-15 00:00:00,950,0,900,50,Okearin
76,2022-03-16 00:00:00,900,0,850,50,Okearin
77,2022-03-17 00:00:00,850,0,800,50,Okearin
78,2022-03-18 00:00:00,800,0,750,50,Okearin
79,2022-03-21 00:00:00,750,0,700,50,Okearin
80,2022-03-22 00:00:00,700,0,650,50,Okearin
81,2022-03-23 00:00:00,650,0,560,90,Okearin
82,2022-03-24 00:00:00,560,0,560,0,Okearin
83,2022-03-25 00:00:00,560,0,500,60,Okearin
84,2022-03-28 00:00:00,500,0,450,50,Okearin
85,2022-03-29 00:00:00,450,0,400,50,Okearin
86,2022-03-30 00:00:00,400,0,350,50,Okearin
87,2022-03-31 00:00:00,350,1700,300,50,Okearin
88,2022-04-01 00:00:00,2000,0,1920,80,Okearin
89,2022-04-04 00:00:00,1920,0,1900,20,Okearin
90,2022-04-05 00:00:00,1900,0,1800,100,Okearin
91,2022-04-06 00:00:00,1800,0,1800,0,Okearin
92,2022-04-07 00:00:00,1800,0,1700,100,Okearin
93,2022-04-08 00:00:00,1700,0,1700,0,Okearin
94,2022-04-11 00:00:00,1700,0,1600,100,Okearin
95,2022-04-12 00:00:00,1600,0,1600,0,Okearin
96,2022-04-13 00:00:00,1600,0,1500,100,Okearin
97,2022-04-14 00:00:00,1500,0,1500,0,Okearin
100,2022-04-19 00:00:00,1500,0,1400,100,Okearin
101,2022-04-20 00:00:00,1400,0,1400,0,Okearin
102,2022-04-21 00:00:00,1400,0,1310,90,Okearin
103,2022-04-22 00:00:00,1310,0,1310,0,Okearin
104,2022-04-25 00:00:00,1310,0,1300,10,Okearin
105,2022-04-26 00:00:00,1300,0,1210,90,Okearin
106,2022-04-27 00:00:00,1210,0,1210,0,Okearin
107,2022-04-28 00:00:00,1210,0,1150,60,Okearin
108,2022-04-29 00:00:00,1150,0,1100,50,Okearin
109,30/4/2022,1100,0,1100,0,Okearin
111,2022-05-04 00:00:00,1100,0,1050,50,Okearin
112,2022-05-05 00:00:00,1050,0,1000,50,Okearin
113,2022-05-06 00:00:00,1000,0,950,50,Okearin
114,2022-05-09 00:00:00,950,0,900,50,Okearin
115,2022-05-10 00:00:00,900,0,850,50,Okearin
116,2022-05-11 00:00:00,850,0,850,0,Okearin
117,2022-05-12 00:00:00,850,1100,750,100,Okearin
118,2022-05-13 00:00:00,1850,0,1850,0,Okearin
119,2022-05-16 00:00:00,1850,0,1750,100,Okearin
120,2022-05-17 00:00:00,1750,0,1700,50,Okearin
121,2022-05-18 00:00:00,1700,0,1650,50,Okearin
122,2022-05-19 00:00:00,1650,0,1600,50,Okearin
123,2022-05-20 00:00:00,1600,0,1600,0,Okearin
124,2022-05-23 00:00:00,1600,0,1550,50,Okearin
125,2022-05-24 00:00:00,1550,0,1500,50,Okearin
126,2022-05-25 00:00:00,1500,0,1450,50,Okearin
127,2022-05-26 00:00:00,1450,0,1400,50,Okearin
128,2022-05-27 00:00:00,1400,0,1350,50,Okearin
129,2022-05-28 00:00:00,1350,0,1350,0,Okearin
130,2022-05-30 00:00:00,1350,0,1200,100,Okearin
131,2022-05-31 00:00:00,1250,0,1250,0,Okearin
132,2022-06-01 00:00:00,1250,0,1170,80,Okearin
133,2022-06-02 00:00:00,1170,0,1170,0,Okearin
134,2022-06-03 00:00:00,1170,0,1100,70,Okearin
135,2022-06-06 00:00:00,1100,0,1100,0,Okearin
136,2022-06-07 00:00:00,1100,0,1000,100,Okearin
137,2022-06-08 00:00:00,1000,0,1000,0,Okearin
138,2022-06-09 00:00:00,1000,0,950,50,Okearin
139,2022-06-10 00:00:00,950,0,900,50,Okearin
140,2022-06-14 00:00:00,900,0,850,50,Okearin
141,2022-06-15 00:00:00,850,0,800,50,Okearin
142,2022-06-16 00:00:00,800,0,800,0,Okearin
143,2022-06-17 00:00:00,800,0,750,50,Okearin
144,2022-06-20 00:00:00,750,0,700,50,Okearin
145,2022-06-21 00:00:00,700,0,650,50,Okearin
146,2022-06-22 00:00:00,650,0,600,50,Okearin
147,2022-06-23 00:00:00,600,0,600,0,Okearin
148,2022-06-24 00:00:00,600,0,500,100,Okearin
149,2022-06-27 00:00:00,500,0,500,0,Okearin
150,2022-06-28 00:00:00,500,0,450,50,Okearin
151,2022-06-29 00:00:00,450,0,400,50,Okearin
152,2022-06-30 00:00:00,400,0,350,50,Okearin
153,2022-07-01 00:00:00,350,860,350,0,Okearin
154,2022-07-04 00:00:00,1210,0,1150,60,Okearin
155,2022-07-05 00:00:00,1150,0,1150,0,Okearin
156,2022-07-06 00:00:00,1150,0,1100,50,Okearin
157,2022-07-07 00:00:00,1100,0,1050,50,Okearin
158,2022-07-08 00:00:00,1050,0,1050,0,Okearin
159,2022-07-13 00:00:00,1050,0,1000,50,Okearin
160,2022-07-14 00:00:00,1000,0,950,50,Okearin
161,2022-07-15 00:00:00,950,0,900,50,Okearin
162,2022-07-18 00:00:00,900,0,850,50,Okearin
163,2022-07-19 00:00:00,850,0,850,0,Okearin
164,2022-07-20 00:00:00,850,0,800,50,Okearin
165,2022-07-21 00:00:00,800,0,750,50,Okearin
166,2022-07-22 00:00:00,750,0,700,50,Okearin
167,2022-07-23 00:00:00,700,0,700,0,Okearin
168,2022-07-25 00:00:00,700,0,650,50,Okearin
169,2022-07-26 00:00:00,650,0,650,0,Okearin
170,2022-07-27 00:00:00,650,0,600,50,Okearin
171,2022-07-28 00:00:00,600,1440,550,50,Okearin
172,2022-07-29 00:00:00,1990,0,1950,40,Okearin
173,2022-07-30 00:00:00,1950,0,1900,50,Okearin
174,2022-08-01 00:00:00,1900,0,1900,0,Okearin
175,2022-08-02 00:00:00,1900,0,1850,50,Okearin
176,2022-08-03 00:00:00,1850,0,1800,50,Okearin
177,2022-08-04 00:00:00,1800,0,1800,0,Okearin
178,2022-08-05 00:00:00,1800,0,1750,50,Okearin
179,2022-08-08 00:00:00,1750,0,1750,0,Okearin
180,2022-08-09 00:00:00,1750,0,1750,0,Okearin
181,2022-08-10 00:00:00,1750,0,1700,50,Okearin
182,2022-08-11 00:00:00,1700,0,1700,0,Okearin
183,2022-08-12 00:00:00,1700,0,1650,50,Okearin
184,2022-08-15 00:00:00,1650,0,1650,0,Okearin
185,2022-08-16 00:00:00,1650,0,1600,50,Okearin
186,2022-08-17 00:00:00,1600,0,1550,50,Okearin
187,2022-08-18 00:00:00,1550,0,1550,0,Okearin
188,2022-08-19 00:00:00,1550,0,1500,50,Okearin
189,2022-08-22 00:00:00,1500,0,1450,50,Okearin
190,2022-08-23 00:00:00,1450,0,1450,0,Okearin
191,2022-08-24 00:00:00,1450,0,1400,50,Okearin
192,2022-08-25 00:00:00,1400,0,1350,50,Okearin
193,2022-08-26 00:00:00,1350,0,1350,0,Okearin
194,2022-08-29 00:00:00,1350,0,1300,50,Okearin
195,44803,1300,0,1250,50,Okearin
196,44804,1250,0,1250,0,Okearin
14,2020-03-17 00:00:00,SOTU,6:03PM,09:58HRS,0,Onitsha2
15,2020-03-18 00:00:00,SOTU,6:45PM,10:57HRS,0,Onitsha2
16,2020-03-19 00:00:00,SOTU,6:28PM,10:45HRS,0,Onitsha2
17,2020-03-20 00:00:00,SOTU,6:28PM,09:24HRS,0,Onitsha2
18,2020-03-23 00:00:00,CHIDINMA,6:01PM,09:31HRS,0,Onitsha2
19,2020-03-24 00:00:00,CHIDINMA,5:51PM,09:25HRS,0,Onitsha2
20,2020-03-25 00:00:00,CHIDINMA,5:55PM,09:12HRS,0,Onitsha2
21,2020-03-26 00:00:00,CHIDINMA,0,0,0,Onitsha2
22,2020-03-27 00:00:00,CHIDINMA,0,0,0,Onitsha2
195,2022-07-01 00:00:00,4660,0,4660,0,Onitsha
197,2022-07-02 00:00:00,4610,0,4610,50,Onitsha
198,2022-07-05 00:00:00,4570,0,4570,40,Onitsha
199,2022-07-06 00:00:00,4550,0,4550,20,Onitsha
200,2022-07-07 00:00:00,4500,0,4500,50,Onitsha
201,2022-07-08 00:00:00,4440,0,4440,60,Onitsha
203,2022-07-09 00:00:00,4410,0,4410,30,Onitsha
207,2022-07-13 00:00:00,4390,0,4390,20,Onitsha
209,2022-07-14 00:00:00,4370,0,4370,20,Onitsha
211,2022-07-15 00:00:00,4340,0,4340,30,Onitsha
212,2022-07-16 00:00:00,4310,0,4310,30,Onitsha
213,2022-07-19 00:00:00,4285,0,4285,25,Onitsha
214,2022-07-20 00:00:00,4235,0,4235,50,Onitsha
215,2022-07-21 00:00:00,4175,0,4175,60,Onitsha
217,2022-07-22 00:00:00,4140,0,4140,35,Onitsha

In [171]:
def remove_whitespace():
    for col in df.columns:
        df[col].str.strip()

In [194]:
# Structuring the datatypes
df['Date'] = df['Date'].astype('datetime64')

df['Diesel_Tank_Opening_Quantity'] = df['Diesel_Tank_Opening_Quantity'].astype('int')

df['Quantity_of_Diesel_Supplied'] = df['Quantity_of_Diesel_Supplied'].astype('int')

df['Diesel_Tank_Closing_Quantity'] = df['Diesel_Tank_Closing_Quantity'].astype('int')

df['Difference_In_Diesel_Quantity'] = df['Difference_In_Diesel_Quantity'].astype('int')

df['Difference_In_Diesel_Quantity_Calc'] = df['Diesel_Tank_Opening_Quantity'] - df['Diesel_Tank_Closing_Quantity']
# Checking if correct
df['Truth'] = df['Difference_In_Diesel_Quantity'] == df['Difference_In_Diesel_Quantity_Calc']

df['Truth'].value_counts()

n_steps = 2
def rolling_diff(x):
    return x.iloc[-1] - x.iloc[0]

df['Refill_Check']=df.Diesel_Tank_Opening_Quantity.rolling(window=n_steps).apply(rolling_diff).fillna(-1)

df['Refilling Check2'] = df['Refill_Check'] > 0
df

C:\Users\Tobiloba\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py:1163: UserWarning: Parsing '19/08/2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  to_datetime(arr).values,

ValueError: mixed datetimes and integers in passed array

In [176]:
df['site'].value_counts()

Okearin      169
Apapa        168
Oshodi       167
Tradefair    163
Onitsha       44
Ikeja sg      33
Ikeja bg      22
Aba           11
Onitsha2       9
Name: site, dtype: int64

In [193]:
df[df['site']=='Onitsha2']

,Date,Diesel_Tank_Opening_Quantity,Quantity_of_Diesel_Supplied,Diesel_Tank_Closing_Quantity,Difference_In_Diesel_Quantity,site
14,2020-03-17 00:00:00,SOTU,6:03PM,09:58HRS,0,Onitsha2
15,2020-03-18 00:00:00,SOTU,6:45PM,10:57HRS,0,Onitsha2
16,2020-03-19 00:00:00,SOTU,6:28PM,10:45HRS,0,Onitsha2
17,2020-03-20 00:00:00,SOTU,6:28PM,09:24HRS,0,Onitsha2
18,2020-03-23 00:00:00,CHIDINMA,6:01PM,09:31HRS,0,Onitsha2
19,2020-03-24 00:00:00,CHIDINMA,5:51PM,09:25HRS,0,Onitsha2
20,2020-03-25 00:00:00,CHIDINMA,5:55PM,09:12HRS,0,Onitsha2
21,2020-03-26 00:00:00,CHIDINMA,0,0,0,Onitsha2
22,2020-03-27 00:00:00,CHIDINMA,0,0,0,Onitsha2